stages:
  - test
  - deploy

prepare:
  stage: test
  image: registry.networkteam.com/networkteam/build/php81
  script:
    - composer test:prepare
  artifacts:
    paths:
      - .Build

phpstan:
  stage: test
  image: registry.networkteam.com/networkteam/build/php81
  script:
    - composer phpstan
  dependencies:
    - prepare

phpcs:
  stage: test
  image: registry.networkteam.com/networkteam/build/php81
  script:
    - composer phpcs
  dependencies:
    - prepare

deploy:
  stage: deploy
  image: curlimages/curl:7.74.0
  script:
    - 'curl -v --header "Job-Token: $CI_JOB_TOKEN" --data "tag=$CI_COMMIT_TAG" "https://gitlab.networkteam.com/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    refs:
      - tags
