
Networkteam:
  Neos:
    Util:
      locales: ['de_DE.utf8', 'de_DE', 'de']
      dateHelper:
        timezone: 'Europe/Berlin'

Neos:
  Neos:
    fusion:
      autoInclude:
        Networkteam.Neos.Util: true
  Fusion:
    defaultContext:
      Networkteam.Neos.Util.Caching: Networkteam\Neos\Util\Eel\CachingHelper
      Networkteam.Neos.Util.String: Networkteam\Neos\Util\Eel\StringHelper
      Networkteam.Neos.Util.Format.SanitizedId: Networkteam\Neos\Util\Sanitizer\StringToIdSanitizer
      Networkteam.Neos.Util.Date: Networkteam\Neos\Util\Eel\DateHelper
      Networkteam.Neos.Util.Hash: Networkteam\Neos\Util\Eel\HashHelper
      Networkteam.Neos.Util.Array: Networkteam\Neos\Util\Eel\ArrayHelper
